### ISSUE TITLE
include_lib not found

### ISSUE THREAD

**Issue by hachreak** [vim-erlang/vim-erlang-compiler#17]
Hi,
I'm using all the plugins to works on a project that implement a REST API with webmachine.

In my resource I have:

```erlang
-include_lib("webmachine/include/webmachine.hrl").
```

But vim say me that `can't find include lib "webmachine/include/webmachine.hrl"`.
Can someone help me? I have not an precise idea how I can fix this problem.

Thanks a lot!

**Comment by hcs42** [comment]
Hi,

Which tool do you use to build your project? vim-erlang-compiler currently supports rebar (version 2), and it also has some rudimentary support for Makefiles.

Where is "webmachine/include/webmachine.hrl" located wrt your source files? I.e. how does the directory structure of your project look like?

**Comment by hachreak** [comment]
I'm using `rebar3`.
this is my `rebar.config`:
```erlang
{erl_opts, [debug_info]}.
{deps, [
  {webmachine, {git, "git://github.com/basho/webmachine", {branch, master}}},
  {oauth2, {git, "git://github.com/kivra/oauth2", {branch, master}}},
  {jsx, {git, "https://github.com/talentdeficit/jsx.git", {branch, master}}},
  {oauth2_mongopool,
   {git, "https://github.com/hachreak/oauth2_mongopool.git", {branch, master}}}
]}.
```

The structure of my project:
```
_build
priv
README.md
rebar.config
rebar.lock
src
start.sh
utils
```

if you need any other information, please tell me! :)

**Comment by hcs42** [comment]
Thanks, it seems that rebar3 stores the dependencies in the `_build/<profile>/lib` directory.

Could you try my [rebar3 branch][1]? I added the `_build/<profile>/lib/*/ebin` directories to the Erlang path, which makes the compiler find the hrl.

[1]: https://github.com/hcs42/vim-erlang-compiler/commits/rebar3

**Comment by fishcakez** [comment]
I don't think that's the right fix for rebar3. We should only use one profile. I would suggest using the test profile when in test/ and default otherwise. It might be we would want a configuration for rebar3 to set the profile to use. But that could wait until someone wants it.

After the holiday season I will see about writing a rebar3 provider for this because it's unlikely we will handle everything correctly without using rebar3.

**Comment by fishcakez** [comment]
Well unless you want to or dont want that apporach @hcs42. I am only suggesting it as I might be more familiar with rebar3.

**Comment by hcs42** [comment]
> We should only use one profile. I would suggest using the test profile when in test/ and default otherwise.

I don't know much about profiles, but this sounds sensible. Do most people use the "default" and "test" profiles?

> After the holiday season I will see about writing a rebar3 provider for this because it's unlikely we will handle everything correctly without using rebar3.

If providers are the proper way to do it, I'm open to that.

**Comment by fishcakez** [comment]
Those profiles are the defaults. So rebar3 compile will build with the
default profile when no profile is set. Rebar3 ct or eunit will use the
test profile auotmatically which also compile all files in test/.

I think using rebar3 provider is the way to go because we probably don't
want to reimplement profile merging and other things. It shouldn't be too
slow.

**Comment by fishcakez** [comment]
As an aside, when multiple profiles are used they combine to
_build/profile1+profile2/ not use both build directories.

**Comment by hachreak** [comment]
@hcs42 @fishcakez  what about use the command [rebar3 path](https://github.com/erlang/rebar3#features)?

**Comment by fishcakez** [comment]
I didn't know about `rebar3 path` but that looks perfect here!

**Comment by hcs42** [comment]
@hachreak Do you feel like modifying my [rebar3 commit][1] to use rebar3 path?

[1]: https://github.com/hcs42/vim-erlang-compiler/commits/rebar3

**Comment by akalyaev** [comment]
Looks like rebar3 is going to be a standard de facto. Looking forward to seeing support for it

**Comment by hachreak** [comment]
Yep :) , in the `Erlang Factory SF 2016` 10 days ago they [announced](https://www.youtube.com/watch?v=YlNrWxH56_E) the adoption... XD
And here you can see the [confirm](https://github.com/erlang/rebar3) of that.
