### ISSUE TITLE
Infinite recursion when trying to find rebar config files in windows

### ISSUE THREAD

**Issue by brainstormi** [vim-erlang/vim-erlang-compiler#18]
when finding rebar.config files in windows it generates an infinite recursion due to not being able to match root directory path while transversing the tree
```
find_files("/", Files) ->
    find_file("/", Files);
find_files(Path, Files) ->
    ...
```
In Windows, Erlang root path would be "c:/" (or driveX:/") in contrast with UNIX systems "/". Current erlang script only take in account UNIX filesystem, generating an infinite recursion in Windows environment.

**Comment by hcs42** [comment]
@brainstormi I created a PR: https://github.com/vim-erlang/vim-erlang-compiler/pull/20

Could you test it?
