### ISSUE TITLE
Cannot handle parse_transform in neovim

### ISSUE THREAD

**Issue by billysvensson** [vim-erlang/vim-erlang-compiler#19]
When I'm adding a parse_transform to my rebar.conf the compiler warnings in neovim stops working for that project. In regular vim it works great though, so I guess it's some minor incompatibility.

The line in rebar.conf that breaks the plugin:
`{erl_opts, [debug_info, {parse_transform, lager_transform}]}.`

**Comment by hcs42** [comment]
Could you elaborate on "neovim stops working for that project"? Thank you.

**Comment by billysvensson** [comment]
It's the compiler warnings/errors that stops working, so it no longer shows anything in the sidebar or statusbar when a file cannot be compiled.

**Comment by billysvensson** [comment]
This was due to a rebar3 incompatibility. A dirty workaround for rebar3 users is to create a deps symlink in your projects root directory: `ln -s _build/default/lib deps`
You may close this ticket if you don't support rebar3.

**Comment by hcs42** [comment]
@billysvensson Could you try if this PR (https://github.com/vim-erlang/vim-erlang-compiler/pull/21) fixes your issue? It adds initial support for rebar 3.

**Comment by billysvensson** [comment]
Yes, PR #21 fixes the issue for me.
