### ISSUE TITLE
Syntax check does not run

### ISSUE THREAD

**Issue by sgerguri** [vim-erlang/vim-erlang-compiler#24]
Plugin works just fine for standalone Erlang files but silently fails to do anything within a rebar3 project.

This is happening on OS X using homebrew-installed Vim (version 7.4, with patches 1-1817) and homebrew-installed rebar3; I am using pathogen to load the plugin. I have tried all manner of things - including removing _everything_ except for pathogen and vim-erlang-compiler and having a pristine .vimrc file, but nothing seems to work.

**Comment by hcs42** [comment]
When you do a :make, Vim prints a line like this:

    :!/home/.../vim-erlang-compiler/compiler/erlang_check.erl --outdir ebin ... myfile.erl 2>&1| tee /var/folders/r3/cj0sy26x2kg5bcb9g48btljh0000gn/T/vq4rwHZ/196

Could you run the same command from the terminal, and append a "-v" option as well for verbosity? E.g.

    /home/.../vim-erlang-compiler/compiler/erlang_check.erl --outdir ebin ... myfile.erl -v

(You need to be in a directory so that the relative path at the end will be correct. Or you can use an absolute file name and then the current directory won't matter.)

The result of that command would help to narrow the problem. Could you attach that as a txt file to this ticket?

**Comment by sgerguri** [comment]
After running:

`~/.vim/bundle/vim-erlang-compiler/compiler/erlang_check.erl --outdir ebin src/my_file.erl -v`

I get the following:

`Verbose mode on.
Found project root: "/Users/shkodran.gerguri/projects/ae/analytics/my-proj"
Try build system: rebar3
Found build file: ["/Users/shkodran.gerguri/projects/ae/analytics/my-proj"] "/Users/shkodran.gerguri/projects/ae/analytics/my-proj/rebar.lock"
Found build file: ["/Users/shkodran.gerguri/projects/ae/analytics/my-proj"] "/Users/shkodran.gerguri/projects/ae/analytics/my-proj/rebar.config"
rebar.config read: /Users/shkodran.gerguri/projects/ae/analytics/my-proj/rebar.config
Found build file: ["/Users/shkodran.gerguri/projects/ae/analytics/my-proj"] "/Users/shkodran.gerguri/projects/ae/analytics/my-proj/rebar3"
Code paths: [".",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/kernel-4.2/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/stdlib-2.8/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/xmerl-1.3.10/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/wx-1.6.1/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/webtool-0.9.1/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/typer-0.9.10/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/tools-2.8.3/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/test_server-3.10/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/syntax_tools-1.7/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/ssl-7.3/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/ssh-4.2.2/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/snmp-5.2.2/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/sasl-2.7/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/runtime_tools-1.9.3/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/reltool-0.7/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/public_key-1.1.1/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/percept-0.8.11/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/parsetools-2.1.1/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/otp_mibs-1.1/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/ose-1.1/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/os_mon-2.4/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/orber-3.8.1/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/odbc-2.11.1/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/observer-2.1.2/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/mnesia-4.13.3/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/megaco-3.18/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/jinterface-1.6.1/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/inets-6.2/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/ic-4.4/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/hipe-3.15/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/gs-1.6/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/eunit-2.2.13/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/et-1.5.1/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/erts-7.3/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/erl_interface-3.8.2/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/erl_docgen-0.4.2/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/eldap-1.2.1/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/edoc-0.7.18/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/diameter-1.11.2/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/dialyzer-2.9/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/debugger-4.1.2/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/crypto-3.6.3/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/cosTransactions-1.3.1/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/cosTime-1.2.1/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/cosProperty-1.2/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/cosNotification-1.2.1/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/cosFileTransfer-1.2/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/cosEventDomain-1.2/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/cosEvent-2.2/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/compiler-6.0.3/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/common_test-1.12/ebin",
             "/usr/local/Cellar/erlang/18.3/lib/erlang/lib/asn1-4.0.2/ebin"]
Compiling: compile:file("/Users/shkodran.gerguri/projects/ae/analytics/my-proj/src/my_file.erl",
    [warn_export_all,warn_export_vars,warn_shadow_vars,warn_obsolete_guard,
     warn_unused_import,report,debug_info,debug_info,
     {parse_transform,lager_transform},
     {outdir,"/Users/shkodran.gerguri/projects/ae/analytics/my-proj/ebin"}])
/Users/shkodran.gerguri/projects/ae/analytics/my-proj/src/my_file.erl: undefined parse transform 'lager_transform'`

**Comment by hcs42** [comment]
The problem is that vim-erlang-compiler should have added the paths in your project (e.g. lager's path) to the code paths. You should see something like `/Users/shkodran.gerguri/projects/ae/analytics/deps/lager/ebin` in there. Since it's not there, the Erlang compiler cannot find the lager module containing the parse transformation when compiling your module.

A few questions:

1. Have you compiled your project with "rebar3 compile"? So is it that the lager beam files are there in your project but vim-erlang-compiler cannot find them?
2. Could you run `rebar3 path` inside your project? vim-erlang-compiler uses the output of that command to extend the code path. It should print a bunch of directories, but my suspicion is that it won't print anything.
3. Do you have the `deps_dir` setting set in rebar.config? That might cause `rebar3 path` not to work properly. I have seen this with @zsoci a few days ago, so if this is the case, we should contact the rebar devs to see if this is a rebar bug.

As a short term workaround, you can edit [erlang_check.erl][2] and add the directories of your dependencies to the code path in the main function:

    code:add_pathsa(filelib:wildcard("/home/myproj/deps/*/ebin"))  % untested

A general workaround for similar problems could be to extend vim-erlang-compiler so that you can add paths to the [g:erlang_make_options_rules][1] variable in your vimrc:

    let g:erlang_make_options_rules =
      \ [{'path_re': 'project_a',
      \   'options': '--outdir . --xref',
      \   'code_paths': ['/home/me/project_a/*/ebin']
      \  }]

[1]: https://github.com/vim-erlang/vim-erlang-compiler/blob/7d6d3d681375e86474635a8c3ebba82f146332f8/doc/vim-erlang-compiler.txt#L74
[2]: https://github.com/vim-erlang/vim-erlang-compiler/blob/7d6d3d681375e86474635a8c3ebba82f146332f8/compiler/erlang_check.erl#L13

**Comment by hcs42** [comment]
Note: there is a rebar3 PR (thanks to @zsoci) which will make "rebar3 path" work correctly even when using "deps_dir": https://github.com/erlang/rebar3/pull/1197

**Comment by sgerguri** [comment]
Hello Csaba,

thanks for investigating this, and apologies about the delayed response on my part, it's been a busy few days.

As for your questions:

1. Nope - I have yet to compile it in this case. Does the plugin require beam files to work? It seems to work on fresh plain .erl files that have yet to be compiled.

2. It prints the path to all the deps the project uses.

3. No, and the project uses a `_build` directory instead of the more traditional rebar2.x `deps` directory. So the dependencies live under `my_project/_build/default/lib/<dependency>`. The sources of the `my_project` end up being copied there automatically by `rebar3` as well. Could this be the reason why it's failing to run the plugin?

**Comment by zsoci** [comment]
Hi Shkodran,

Could you provide your rebar.config file please?

Thanks and kind regards,
Zsolt

**Comment by sgerguri** [comment]
Hello Zsolt,

here goes:

`%%-*- mode: erlang -*-
{deps,
 [{gproc,
   {git, "https://github.com/uwiger/gproc.git", {branch, "master"}}},

  {vesper_common,
   {git, "ssh://git@<private-gitlab>/analytics/vesper-common.git", {branch, "master"}}},
  {actual_qc_types,
   {git, "ssh://git@<private-gitlab>/analytics/<private-dep1>.git", {branch, "master"}}},

  {lager,
   {git, "git@<private-gitlab>:analytics-deps/lager.git", {branch, "master"}}},

  % TODO: not in production
  {proper,
   {git, "https://github.com/manopapad/proper.git", {branch, "master"}}}
 ]}.

{erl_opts,
 [debug_info,
  {parse_transform, lager_transform}]}.

{shell_apps, [my_proj]}.

{relx,
 [{sys_config, "config/sys.config"}
 ]}.

% CT
{ct_opts, [{cover, "test/cover.spec"},
           {basic_html, true}]}.`

I've made some substitutions, where private stuff was used (stuff in <>) but otherwise it is the unmodified config.

**Comment by zsoci** [comment]
Thanks. What is the output of rebar3 path command in the project directory? Is there a lager_transform.beam file in _build/default/lib/lager/ebin?

**Comment by sgerguri** [comment]
Output of `rebar3 path`:

```
/Users/shkodran.gerguri/projects/ae/analytics/my-proj/_build/default/lib/<private1>/ebin /Users/shkodran.gerguri/projects/ae/analytics/my-proj/_build/default/lib/proper/ebin /Users/shkodran.gerguri/projects/ae/analytics/my-proj/_build/default/lib/lager/ebin /Users/shkodran.gerguri/projects/ae/analytics/my-proj/_build/default/lib/gproc/ebin /Users/shkodran.gerguri/projects/ae/analytics/my-proj/_build/default/lib/goldrush/ebin /Users/shkodran.gerguri/projects/ae/analytics/my-proj/_build/default/lib/<private2>/ebin /Users/shkodran.gerguri/projects/ae/analytics/my-proj/_build/default/lib/my_proj/ebin
```

The `lager_transform.beam` file is there.

**Comment by zsoci** [comment]
Thanks. What does 'which rebar3' returns?

**Comment by sgerguri** [comment]
```
$ ls -l $(which rebar3)
lrwxr-xr-x  1 shkodran.gerguri  admin  33 12 May 15:53 /usr/local/bin/rebar3 -> ../Cellar/rebar3/3.1.0/bin/rebar3
```

**Comment by zsoci** [comment]
Seems erlang vim compiler uses rebar3 in your project directory, but when you launch it it comes from /usr/local/bin ->...    could you rename rebar3 in your project and try to vim compile again with the command above please? what is the output?

**Comment by sgerguri** [comment]
It works, and is highlighting the errors. Is that an issue of the project's `rebar3` being older and thus not supporting some of the stuff from the plugin?

**Comment by zsoci** [comment]
Exactly. Please make sure you have the latest official rebar3 binary in your project directory, or delete it from there.
Have a nice day.

**Comment by sgerguri** [comment]
Awesome, thanks for the help @zsoci !
