### ISSUE TITLE
Error highlighting not working

### ISSUE THREAD

**Issue by BrettHemes-3M** [vim-erlang/vim-erlang-compiler#48]
Moving this from discussions as I have tried again on a new fresh Ubuntu install with no other bundles with the same result...

Ubuntu 20.04
Vim 8.1.2269

I recently got a new Ubuntu 20.04 install going and am having trouble with my new Vim install in combination with `vim-erlang-compiler`.  Long story short, syntax errors are not highlighting.

On save (`:w`) seemingly nothing happens.  If I run `:make` I get good (expected) error listings and then the prompt

    Press ENTER or type command to continue

after pressing `Enter` Vim displays at the bottom something like

    "file_at_hand.erl:##" [New File]
    (1 of #): error_number_1_listing
    Press ENTER or type command to continue

after pressing `Enter` here I presented with a new buffer named `file_at_hand.erl:##` where `##` is the line number of the first error.

Then nothing...  If I close the new buffer I am back at the original file and I can edit as normal.  Its like something is getting stuck as it is generating the error messages and corresponding highlighting?

**Comment by hcs42** [comment]
Do you use Erlang 24?

I suspect that the Erlang compiler's output format was changed in Erlang 24, and the plugin cannot parse it.

I will check whether the plugin works with Erlang 24 on my machine, and if not, I will adjust it to work with the Erlang 24 too.

**Comment by BrettHemes** [comment]
Indeed, this new install is with OTP 24

**Comment by hcs42** [comment]
@BrettHemes 

I fixed the problem in my [`issue_48`](https://github.com/hcs42/vim-erlang-compiler/commits/issue_48) branch.

Could you try it?

**Comment by BrettHemes** [comment]
I am unsure of how to force Vundle to use a non-default branch.  Do you know?

**Comment by BrettHemes** [comment]
OK, I was able to figure out how to test this and have confirmed it is working with my setup and OTP 24  👍

**Comment by hcs42** [comment]
Thank you. The fix is now available in the master branch too.
